### ISSUE TITLE
Unable to connect to ODM on Cloud instances. (Self signed certificate error)

### ISSUE THREAD

**Issue by hhdiazlo** [ODMDev/odm-decision-forms#1]
Error reading Swagger file
Status: INTERNAL SERVER ERROR
Message: Error reading swagger: self signed certificate

Found same behavior with a Liberty Profile Server running on local host.

**Comment by amelki** [comment]
[](url)

**Comment by amelki** [comment]
See #2

**Comment by amelki** [comment]
As seen with @hhdiazlo, the parameters passed were not the correct ones. I am closing the issue.
However, we should give more feedback in such a case. See  #2
